[project]
name = "yasha"
version = "0.1.0"
description = "Yet another self-hosted agent"
authors = [
    { name = "Alex Margarit" }
]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = "==3.12.10"
dependencies = [
    "argparse==1.4.0",
    "asyncio==4.0.0",
    "bitsandbytes==0.47.0",
    "fastapi==0.116.1",
    "flashinfer-python==0.3.1",
    "httpx==0.28.1",
    "kokoro==0.9.2",
    "numpy==2.2.6",
    "orpheus-speech==0.1.0",
    "piper-tts==1.3.0",
    "pydantic==2.11.7",
    "pydantic-yaml==1.6.0",
    "python-multipart==0.0.20",
    "ray[data,default,serve-grpc]==2.48.0",
    "scipy==1.16.1",
    "timm==1.0.19",
    "torch==2.8.0",
    "torchaudio==2.8.0",
    "torchvision==0.23.0",
    "transformers==4.56.1",
    "vllm[audio]==0.11.0",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "yasha"
module-root = ""
